%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%          Generated by MATLAB 24.2 and Fixed-Point Designer 24.2          %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [locations,valid] = peakPicker_wrapper_fixpt(xcorr,threshold)
    fm = get_fimath();
    xcorr_in = fi( xcorr, 0, 14, 21, fm );
    threshold_in = fi( threshold, 0, 14, 21, fm );
    [locations_out,valid_out] = peakPicker_fixpt( xcorr_in, threshold_in );
    locations = double( locations_out );
    valid = valid_out;
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
